// Generated by gencpp from file hello_world/addTwoNumbers.msg
// DO NOT EDIT!


#ifndef HELLO_WORLD_MESSAGE_ADDTWONUMBERS_H
#define HELLO_WORLD_MESSAGE_ADDTWONUMBERS_H

#include <ros/service_traits.h>


#include <hello_world/addTwoNumbersRequest.h>
#include <hello_world/addTwoNumbersResponse.h>


namespace hello_world
{

struct addTwoNumbers
{

typedef addTwoNumbersRequest Request;
typedef addTwoNumbersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addTwoNumbers
} // namespace hello_world


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_world::addTwoNumbers > {
  static const char* value()
  {
    return "875493d2ec8f0bdc18c62960322c94b7";
  }

  static const char* value(const ::hello_world::addTwoNumbers&) { return value(); }
};

template<>
struct DataType< ::hello_world::addTwoNumbers > {
  static const char* value()
  {
    return "hello_world/addTwoNumbers";
  }

  static const char* value(const ::hello_world::addTwoNumbers&) { return value(); }
};


// service_traits::MD5Sum< ::hello_world::addTwoNumbersRequest> should match
// service_traits::MD5Sum< ::hello_world::addTwoNumbers >
template<>
struct MD5Sum< ::hello_world::addTwoNumbersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_world::addTwoNumbers >::value();
  }
  static const char* value(const ::hello_world::addTwoNumbersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_world::addTwoNumbersRequest> should match
// service_traits::DataType< ::hello_world::addTwoNumbers >
template<>
struct DataType< ::hello_world::addTwoNumbersRequest>
{
  static const char* value()
  {
    return DataType< ::hello_world::addTwoNumbers >::value();
  }
  static const char* value(const ::hello_world::addTwoNumbersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_world::addTwoNumbersResponse> should match
// service_traits::MD5Sum< ::hello_world::addTwoNumbers >
template<>
struct MD5Sum< ::hello_world::addTwoNumbersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_world::addTwoNumbers >::value();
  }
  static const char* value(const ::hello_world::addTwoNumbersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_world::addTwoNumbersResponse> should match
// service_traits::DataType< ::hello_world::addTwoNumbers >
template<>
struct DataType< ::hello_world::addTwoNumbersResponse>
{
  static const char* value()
  {
    return DataType< ::hello_world::addTwoNumbers >::value();
  }
  static const char* value(const ::hello_world::addTwoNumbersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_WORLD_MESSAGE_ADDTWONUMBERS_H
