// Generated by gencpp from file hello_world/HelloRos.msg
// DO NOT EDIT!


#ifndef HELLO_WORLD_MESSAGE_HELLOROS_H
#define HELLO_WORLD_MESSAGE_HELLOROS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_world
{
template <class ContainerAllocator>
struct HelloRos_
{
  typedef HelloRos_<ContainerAllocator> Type;

  HelloRos_()
    : Ros()  {
    }
  HelloRos_(const ContainerAllocator& _alloc)
    : Ros(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Ros_type;
  _Ros_type Ros;





  typedef boost::shared_ptr< ::hello_world::HelloRos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_world::HelloRos_<ContainerAllocator> const> ConstPtr;

}; // struct HelloRos_

typedef ::hello_world::HelloRos_<std::allocator<void> > HelloRos;

typedef boost::shared_ptr< ::hello_world::HelloRos > HelloRosPtr;
typedef boost::shared_ptr< ::hello_world::HelloRos const> HelloRosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_world::HelloRos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_world::HelloRos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hello_world::HelloRos_<ContainerAllocator1> & lhs, const ::hello_world::HelloRos_<ContainerAllocator2> & rhs)
{
  return lhs.Ros == rhs.Ros;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hello_world::HelloRos_<ContainerAllocator1> & lhs, const ::hello_world::HelloRos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hello_world

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hello_world::HelloRos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_world::HelloRos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_world::HelloRos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_world::HelloRos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_world::HelloRos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_world::HelloRos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_world::HelloRos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42b99dd7c78b4fea28033dec125a8f7f";
  }

  static const char* value(const ::hello_world::HelloRos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42b99dd7c78b4feaULL;
  static const uint64_t static_value2 = 0x28033dec125a8f7fULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_world::HelloRos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_world/HelloRos";
  }

  static const char* value(const ::hello_world::HelloRos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_world::HelloRos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ros Messages\n"
"string Ros\n"
;
  }

  static const char* value(const ::hello_world::HelloRos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_world::HelloRos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Ros);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HelloRos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_world::HelloRos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_world::HelloRos_<ContainerAllocator>& v)
  {
    s << indent << "Ros: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Ros);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_WORLD_MESSAGE_HELLOROS_H
